# Generated by Django 3.2 on 2021-06-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0002_auto_20210323_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='pinned',
            field=models.SmallIntegerField(default=0),
        ),
    ]
