# Generated by Django 3.2 on 2021-06-08 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_forum_app', '0003_forumpost_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='subscribed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
