# Generated by Django 3.2 on 2021-06-08 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_forum_app', '0004_forumpost_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='subscribed',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
