# Generated by Django 3.2 on 2021-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0006_auto_20210609_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='location',
            field=models.CharField(
                choices=[
                    ('AI',
                     'Any'),
                    ('AY',
                     'Alderney'),
                    ('GY',
                     'Guernsey'),
                    ('JE',
                     'Jersey'),
                    ('SK',
                     'Sark')],
                default='AI',
                max_length=2),
        ),
    ]
