# Generated by Django 3.1.7 on 2021-03-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
