# Generated by Django 3.2 on 2021-05-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0003_auto_20210327_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='e1a1873f-0bb9-41e6-a783-479cded558b5', help_text='span class="tinfo">Your display name will be shown                         in the forum and will be part of the link to your personal page.                          It must be *different* to your username. It must be unique.                          Perhaps use your first name and last name, or maybe your business name.                         It will be converted to an internet friendly name when you save it.                         You can change it later...</span>', max_length=37, unique=True),
        ),
    ]
