# Generated by Django 3.2 on 2021-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0003_auto_20210327_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='3ba7673a-5737-4ba9-b0b8-70f7b3d34e48', max_length=37, unique=True),
        ),
    ]
