# Generated by Django 3.2 on 2021-05-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0004_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='e24b7c7f-7695-4cc2-b50f-078aad5b2b3a', help_text='bob', max_length=37, unique=True),
        ),
    ]
