# Generated by Django 3.2 on 2021-05-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0005_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='e9561fa5-a443-4c74-8c58-cdea15f74ef1', max_length=37, unique=True),
        ),
    ]
