# Generated by Django 3.2 on 2021-05-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0006_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(
                blank=True,
                default='f9eb93b6-735e-4e19-ab94-0fe74f314628',
                max_length=37,
                unique=True),
        ),
    ]
