# Generated by Django 3.2 on 2021-05-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0007_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(
                blank=True,
                default='b02c88ce-9b77-4517-8db7-448ffadf3236',
                max_length=37,
                unique=True),
        ),
    ]
