# Generated by Django 3.2 on 2021-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0008_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(
                blank=True,
                default='Please Set A Display Name',
                max_length=37,
                unique=True),
        ),
    ]
