"""
Django settings for django_forum project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import sys, os
from django.urls import reverse_lazy
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path('/opt/django_forum/django_forum/')

# import os
# import shutil


# for root, dirs, files in os.walk('/usr/local/lib/python3.9/site-packages/django'):
#     for directory in dirs:
#         if directory == '__pycache__':
#             shutil.rmtree(os.path.join(root, directory))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xt==^l@8&77h0lyorjl&21va$6@fr0k7wb3@shw!h#%ch8(=_#'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django_forum_app',
    'django_profile',
    'django_posts_and_comments',
    'django_users_app',
    'django_email_verification',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'captcha', #django-recaptcha
    'tinymce',
    'debug_toolbar',
    'sorl.thumbnail',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    #'django.middleware.cache.UpdateCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.cache.FetchFromCacheMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_users_app.middleware.ReauthenticateMiddleware',
]

ROOT_URLCONF = 'django_forum.urls'
TEMPLATE_DIR = os.path.join(BASE_DIR, '/django_forum/django_forum/templates')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_forum.wsgi.application'

#PROFILE_MODEL = Profile

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

if 'pytest' in sys.modules:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': '/etc/opt/django_forum/db.sqlite3',
    }
}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'django_forum_db',
            'USER': 'django_forum_db_user',
            'PASSWORD': '3cX18eZ9v',
            'HOST': '127.0.0.1',
            'PORT': '5432',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

# needed for django debug toolbar

INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, STATIC_URL)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

CONTENT_TYPES = ['image', 'video']
# 2.5MB - 2621440
# 5MB - 5242880
# 10MB - 10485760
# 20MB - 20971520
# 50MB - 52428800
# 100MB 104857600
# 250MB - 214958080
# 500MB - 429916160
MAX_UPLOAD_SIZE = 10485760
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o700
FILE_UPLOAD_PERMISSIONS = 0o644

# django_users_app

LOGIN_REDIRECT_URL = reverse_lazy('forum_post_list_view')
LOGOUT_REDIRECT_URL = reverse_lazy('landing_page')
LOGIN_URL = reverse_lazy('login')

THUMBNAIL_SIZE = (120,120)
THUMBNAIL_DEBUG = True
#THUMBNAIL_ENGINE = 'sorl.thumbnail.engines.wand_engine.Engine'
MAX_USER_IMAGES = 3
# django_forum_app

IMAGE_UPLOAD_PATH = '/uploads/users/'
# DJANOG-EMAIL-VERIFICATION SETTINGS

def verified_callback(user):
    user.is_active = True

EMAIL_VERIFIED_CALLBACK = verified_callback
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_ACTIVE_FIELD = 'is_active'
EMAIL_SERVER = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_ADDRESS = 'slomopots@gmail.com'
EMAIL_FROM_ADDRESS = 'noreply@slomopots.com'
EMAIL_PASSWORD = 'jrouzcgkfszfwggb' # os.environ['password_key'] suggested
EMAIL_MAIL_SUBJECT = 'Confirm your email'
EMAIL_MAIL_HTML = 'emails/mail_body.html'
EMAIL_MAIL_PLAIN = 'emails/mail_body.txt'
EMAIL_PAGE_TEMPLATE = 'registration/confirm.html'
EMAIL_PAGE_DOMAIN = 'http://127.0.0.1:8000/'
EMAIL_TOKEN_LIFE = 60 * 60


## RECAPTCHA SETTINGS

#RECAPTCHA_PUBLIC_KEY = '6LflMicaAAAAAEwcTpcHEZksbYBQV3SGPs8CS24C'
# google testing public key '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
#'6LflMicaAAAAAEwcTpcHEZksbYBQV3SGPs8CS24C'
# RECAPTCHA_PRIVATE_KEY = '6LflMicaAAAAAG1-zUNnySQf_F2lkBlIvGyX7nna'
# google testing private key '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']
#'6LflMicaAAAAAG1-zUNnySQf_F2lkBlIvGyX7nna'


## SESSION SETTINGS
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 129600 # 36 hours.  # defaults to two weeks
SESSION_COOKIE_SECURE = False    # set this to true when using https
# SESSION_SAVE_EVERY_REQUEST = True  #updates timestamp to increase session_cookie_age


# settings for bleach

ALLOWED_TAGS = [
    'a', 'div', 'p', 'span', 'img', 'iframe', 'em', 'i', 'li', 'ol', 'ul', 'strong', 'br',
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'table', 'tbody', 'thead', 'tr', 'td',
    'abbr', 'acronym', 'b', 'blockquote', 'code', 'strike', 'u', 'sup', 'sub',
]

STYLES = [
    'background-color', 'font-size', 'line-height', 'color', 'font-family'
]

ATTRIBUTES = {
    '*': ['style', 'align', 'title', ],
    'a': ['href', ],
    'iframe': ['src', 'height', 'width', 'allowfullscreen'],
}

# testing

if 'test' in sys.argv:
    CAPTCHA_TEST_MODE = True

TINYMCE_DEFAULT_CONFIG = {
    "menubar": False,
    "min-height": "500px",
    "browser_spellcheck": True,
    "contextmenu": False,
    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace fullscreen insertdatetime media table paste code help wordcount spellchecker",
    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media template link anchor | a11ycheck ltr rtl | showcomments addcomment table",
    "custom_undo_redo_levels": 10,
    "selector": 'textarea',
    "init_instance_callback": "function (editor) { $(editor.getContainer()).find('button.tox-statusbar__wordcount').click();"
}

# django crispy forms
CRISPY_FAIL_SILENTLY = not DEBUG

CRISPY_TEMPLATE_PACK = "bootstrap4"



CLAMAV_SOCKET = 'tcp://127.0.0.1:3310'


