# Generated by Django 3.2 on 2021-11-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_artisan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_date',
        ),
    ]
