# Generated by Django 3.2.9 on 2021-12-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_artisan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
