# Generated by Django 3.2.9 on 2021-12-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum', '0002_auto_20211118_1648'),
        ('django_artisan', '0002_artisanforumpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanForumComment',
            fields=[
                ('forumcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_forum.forumcomment')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_forum.forumcomment',),
        ),
    ]
