# Generated by Django 3.2.9 on 2022-02-23 15:08

from django.db import migrations, models
import django_artisan.models
import safe_imagefield.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_artisan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanforumprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='artisanforumprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='userproductimage',
            name='file',
            field=safe_imagefield.models.SafeImageField(allowed_extensions=None, check_content_type=False, max_length=250, max_size_limit=2621440, media_integrity=False, scan_viruses=False, upload_to=django_artisan.models.user_directory_path),
        ),
    ]
