# Generated by Django 3.1.7 on 2021-03-23 13:37

from django.db import migrations, models
import django_artisan.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_artisan', '0002_artisanforumprofile_display_personal_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproductimage',
            options={'permissions': [('approve_image', 'Approve Image')]},
        ),
        migrations.AlterField(
            model_name='artisanforumprofile',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=django_artisan.models.user_directory_path, verbose_name='A single image for your personal page'),
        ),
    ]
