# Generated by Django 3.2.9 on 2022-02-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_artisan', '0003_auto_20220223_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanforumprofile',
            name='parish',
        ),
    ]
