# Generated by Django 3.2.9 on 2022-02-10 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_artisan', '0005_auto_20220204_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductimage',
            name='del_id',
            field=models.CharField(default=uuid.UUID('d29ed788-cf27-4f97-acd1-905932623210'), max_length=36, unique=True),
        ),
    ]
