# Generated by Django 3.2.9 on 2022-02-10 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_artisan', '0008_alter_userproductimage_del_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductimage',
            name='del_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
