# Generated by Django 3.2 on 2021-11-14 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_profile', '0001_initial'),
        ('django_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_messages.message')),
                ('title', models.CharField(default='', max_length=100)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='django_profile.profile')),
            ],
            bases=('django_messages.message',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_messages.message')),
                ('post_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='django_posts_and_comments.post')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='django_profile.profile')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_messages.message',),
        ),
    ]
