# Generated by Django 3.2 on 2021-05-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_posts_and_comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='deleted_at',
        ),
    ]
