# Generated by Django 3.2 on 2021-11-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_posts_and_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default='True'),
        ),
    ]
