# Generated by Django 3.2 on 2021-06-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0010_alter_profile_display_name'),
        ('django_posts_and_comments', '0003_auto_20210521_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='comments',
                to='django_posts_and_comments.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='comments',
                to='django_profile.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_profile',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='posts',
                to='django_profile.profile'),
        ),
    ]
