# Generated by Django 3.1.6 on 2021-02-11 19:25

from django.db import migrations, models
import django.db.models.deletion
import django_profile.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('image_file', models.ImageField(upload_to=django_profile.models.user_directory_path)),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(default=0, editable=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='django_profile.profile')),
            ],
        ),
    ]
