# Generated by Django 3.1.6 on 2021-03-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0002_auto_20210302_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_slug',
        ),
        migrations.AddField(
            model_name='profile',
            name='rules_agreed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
