# Generated by Django 3.1.6 on 2021-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profile', '0003_auto_20210304_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rules_agreed',
            field=models.BooleanField(default='False'),
        ),
    ]
