# Generated by Django 3.2 on 2021-11-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
