# Generated by Django 3.2 on 2021-11-10 15:47

from django.db import migrations, models
import django_forum.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=django_forum.models.user_directory_path_avatar)),
            ],
        ),
    ]
