# Generated by Django 3.2 on 2021-11-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ['created_at'], 'permissions': [('approve_comment', 'Approve Comment')]},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_at'], 'permissions': [('approve_post', 'Approve Post')]},
        ),
        migrations.RenameField(
            model_name='forumcomment',
            old_name='moderation',
            new_name='moderation_date',
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='moderation',
            new_name='moderation_date',
        ),
    ]
