# Generated by Django 3.2 on 2021-11-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='location',
        ),
    ]
