# Generated by Django 3.2.9 on 2021-12-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum', '0002_auto_20211118_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcomment',
            name='moderation_date',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='moderation_date',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='commenting_locked',
            field=models.BooleanField(default=False),
        ),
    ]
