# Generated by Django 3.1.6 on 2021-03-07 20:28

from django.db import migrations, models
import django.db.models.deletion
import django_forum_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_profile', '0001_initial'),
        ('django_posts_and_comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=django_forum_app.models.user_directory_path_avatar)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_posts_and_comments.post')),
                ('author', models.CharField(default='', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('moderation', models.DateField(blank=True, default=None, null=True)),
                ('category', models.CharField(choices=[('EV', 'Event'), ('QN', 'Question'), ('GL', 'General'), ('PS', 'Pictures'), ('FS', 'For Sale')], default='GL', max_length=2)),
            ],
            options={
                'ordering': ['-date_created'],
            },
            bases=('django_posts_and_comments.post',),
        ),
        migrations.CreateModel(
            name='ForumProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_profile.profile')),
                ('bio', models.TextField(blank=True, default='', help_text='This is the biographical information that will be presented on your personal page', max_length=500, verbose_name='biographical information, max 500 chars')),
                ('address_line_1', models.CharField(blank=True, default='', max_length=30, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, default='', max_length=30, verbose_name='address line 2')),
                ('parish', models.CharField(blank=True, default='', max_length=30, verbose_name='parish')),
                ('postcode', models.CharField(blank=True, default='', max_length=6, verbose_name='postcode')),
                ('rules_agreed', models.BooleanField(default='False')),
                ('avatar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='django_forum_app.avatar')),
            ],
            bases=('django_profile.profile',),
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_posts_and_comments.comment')),
                ('author', models.CharField(default='', max_length=40)),
                ('active', models.BooleanField(default='True')),
                ('moderation', models.DateField(blank=True, default=None, null=True)),
                ('title', models.SlugField()),
                ('forum_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to='django_forum_app.forumpost')),
            ],
            options={
                'ordering': ['date_created'],
            },
            bases=('django_posts_and_comments.comment',),
        ),
    ]
