# Generated by Django 3.1.6 on 2021-02-08 15:00

from django.db import migrations
import django_forum_app.models
import safe_filefield.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image_file',
            field=safe_filefield.models.SafeImageField(allowed_extensions=None, check_content_type=False, scan_viruses=False, upload_to=django_forum_app.models.user_directory_path_avatar),
        ),
    ]
