# Generated by Django 3.1.6 on 2021-02-11 19:25

from django.db import migrations, models
import django.db.models.deletion
import django_forum_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumProfileImage',
            fields=[
                ('image_file', models.ImageField(upload_to=django_forum_app.models.user_directory_path)),
                ('image_text', models.CharField(default='', max_length=400)),
                ('image_title', models.CharField(default='', max_length=30)),
                ('image_shop_link', models.CharField(default='#', max_length=50)),
                ('image_shop_link_title', models.CharField(default='', max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(default=0, editable=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_images', to='django_forum_app.forumprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
