# Generated by Django 3.1.6 on 2021-03-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumprofileimage',
            name='image_shop_link',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='forumprofileimage',
            name='image_shop_link_title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='forumprofileimage',
            name='image_text',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='forumprofileimage',
            name='image_title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
