# Generated by Django 3.1.6 on 2021-02-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumprofile',
            name='personal_statement',
        ),
        migrations.AddField(
            model_name='forumprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
