# Generated by Django 3.1.6 on 2021-02-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='biographical information'),
        ),
    ]
