# Generated by Django 3.1.6 on 2021-02-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_posts_and_comments', '0010_remove_comment_user_profile'),
        ('django_forum_app', '0002_auto_20210211_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_posts_and_comments.comment')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='django_forum_app.forumprofile')),
            ],
            bases=('django_posts_and_comments.comment',),
        ),
    ]
