# Generated by Django 3.1.6 on 2021-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0002_auto_20210304_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='This is the biographical information that will be presented on your personal page', max_length=500, verbose_name='biographical information, max 500 chars'),
        ),
    ]
