# Generated by Django 3.1.6 on 2021-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0002_auto_20210221_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumprofile',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='address line 1'),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='address line 2'),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='outlets',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='places that sell my stuff'),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='parish',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='parish'),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='shop_web_address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='shop link'),
        ),
    ]
