# Generated by Django 3.1.6 on 2021-02-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0002_auto_20210208_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumprofile',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='outlets',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='parish',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='personal_statement',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='forumprofile',
            name='shop_web_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
