# Generated by Django 3.1.6 on 2021-02-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0002_auto_20210216_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-date_created']},
        ),
    ]
