# Generated by Django 3.1.6 on 2021-02-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0003_auto_20210216_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='active',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='active',
            field=models.BooleanField(default='True'),
        ),
    ]
