# Generated by Django 3.1.6 on 2021-02-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0004_auto_20210217_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='moderation',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='moderation',
            field=models.BooleanField(default='False'),
        ),
    ]
