# Generated by Django 3.1.6 on 2021-02-26 13:07

from django.db import migrations, models
from django.template.defaultfilters import slugify
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0005_auto_20210223_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='slug',
            field=models.SlugField(default=slugify(django.utils.timezone.now)),
            preserve_default=False,
        ),
    ]
