# Generated by Django 3.1.6 on 2021-02-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_forum_app', '0006_forumcomment_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumcomment',
            old_name='slug',
            new_name='title',
        ),
    ]
