# Generated by Django 3.1.6 on 2021-02-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_posts_and_comments', '0006_auto_20210209_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_profile',
        ),
    ]
