# Generated by Django 3.1.6 on 2021-02-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_posts_and_comments', '0008_auto_20210209_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_profile',
            new_name='user_profile',
        ),
    ]
