# Generated by Django 3.1.6 on 2021-02-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_posts_and_comments', '0009_auto_20210209_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_profile',
        ),
    ]
